### PR TITLE
Some changes to the main README.md file to help streamline the instructions

### PR DESCRIPTION
**Pull request by whowutwut**
To partially address #45 

Based on my running of the operator deployment  in my  OpenShift Environment.  These instructions are really to
* simplify the steps 
* allow for more copy/paste solution
* temporarily bridge the gap we have until the OLM method is working 

Once that is in place, the documentation for this repo should really be written towards a  developer that  wants to make changes to the operator and contribute to the  project, not a IBM Spectrum Scale end user. 

I do also want more details to be documented in RTD, but that effort is getting quite  large,  so I wanted to address these changes.

### CODE REVIEW

**Comment by whowutwut** [comment]
Don't merge this yet, I forgot to also commit an updated: `example/spectrum-scale.yaml`

**Comment by whowutwut** [comment]
Added the spectrum-scale.yaml example file, I'm able to take it for now and replace the fields with my own environment.  No more changes planned.

**Comment by whowutwut** [comment]
@yadaven FYI, I checked in a updated example .yaml file here, it's ready for merge if there's no objections or further comments. I don't plan to change anymore in this PR.  The last commit just spelled out "OLM" -> Operator Lifecycle Manager.

**Comment by yadaven** [comment]
> @yadaven FYI, I checked in a updated example .yaml file here, it's ready for merge if there's no objections or further comments. I don't plan to change anymore in this PR. The last commit just spelled out "OLM" -> Operator Lifecycle Manager.

I will push some more examples for different cluster configuration, along with NodeSelector and mapping.

**Comment by whowutwut** [comment]
After talking to @mew2057 I have removed the pieces in the example that would override the defaults.  I believe for consumers of the operator, we want them to pick up the default quay images instead of building and providing their own.

**Comment by whowutwut** [comment]
@yadaven  Should we just create additional example files for those cases that you specified? That could be done with another PR instead of adding to this one.  This example should be a  mininum that users would need  to change to match their scale environment to get  up and running quickly

**Comment by yadaven** [comment]
> @yadaven Should we just create additional example files for those cases that you specified? That could be done with another PR instead of adding to this one. This example should be a mininum that users would need to change to match their scale environment to get up and running quickly

sure, makes sense. Will create new PR for that. Since this yaml file contain minimum attributes required should we name this yaml file accordingly ? e.g spectrum_scale_basic.yaml ? or some other suggestion. Reason I am asking it is because later on when new samples will be added we can add appropriate prefix to it like spectrum_scale_remoteFs.yaml etc.

**Comment by whowutwut** [comment]
Yes, I can rename it to `spectrum_scale_basic.yaml`

**Pull request merged**
